### ISSUE TITLE
navicat pj 被 f 了吗

### ISSUE THREAD

**Issue by norangit** [HyperSine/how-does-navicat-encrypt-password#13]
大兄弟，如题，好不容易找到这儿来，发现 navicat 的 repo 没有了啊

**Comment by norangit** [comment]
```
./navicat-patcher /Applications/Navicat\ Premium.app/
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*                  Version: 4.0                   *
***************************************************

Press Enter to continue or Ctrl + C to abort.

[*] Your Navicat version: 15.0.8

[-] PatchSolution0 ...... Omitted.
[-] PatchSolution1 ...... Omitted.
[-] PatchSolution2 ...... Omitted.
[-] Patch abort. None of PatchSolutions will be applied.
    Are you sure your Navicat has not been patched before?
```

**Comment by HyperSine** [comment]
本账号不会有任何公开的、违反DMCA的内容。navicat-keygen相关的内容这里不会谈及。如有需要邮件联系。

**Comment by qinzeduomoxiong** [comment]
兄弟 你的问题咋解决的啊

**Comment by norangit** [comment]
换工具吧，idea 的datagrip很好用，网上有破解jar ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;qinzeduomoxiong&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月7日(星期天) 下午2:49
收件人:&nbsp;&quot;HyperSine/how-does-navicat-encrypt-password&quot;<how-does-navicat-encrypt-password@noreply.github.com&gt;;
抄送:&nbsp;&quot;jll8&quot;<281170419@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HyperSine/how-does-navicat-encrypt-password] navicat pj 被 f 了吗 (#13)
