### ISSUE TITLE
In regards of supporting Mac OS

### ISSUE THREAD

**Issue by kogisin** [HyperSine/how-does-navicat-encrypt-password#15]
## Problem statement

I have [this prev repository](https://github.com/DoubleLabyrinth/how-does-navicat-encrypt-password), which had `mac` branch, but it seems like it doesn't exist in this newly created project.

Any plans to support MacOS users? 

## General Information 

OS: macOS Catalina Version 10.15.3
Navicat Premium: latest version 15.0.11

## Steps to produce

Using previous repository of `mac` branch, it failed to find pubkey location while running `navicat-patcher`

```shell
./navicat-patcher  /Applications/Navicat\ Premium.app/Contents/MacOS/Navicat\ Premium

Open file successfully.
Get file size successfully: 25469808
Map file successfully.
Failed to find pubkey location.
```

My best guess why this failed to find pubkey location is that maybe I am using the latest version of Navicat and the directory has changed?

**Comment by HyperSine** [comment]
I think you mean navicat-keygen which has been taken down due to DMCA violation. In this account, no copyright infringement content will be uploaded or talked about. If you need any help, please contact via email.
