### ISSUE TITLE
大佬navicat16有破解方法吗

### ISSUE THREAD

**Issue by chenzhixiang111** [HyperSine/how-does-navicat-encrypt-password#24]

**Comment by cmbsolutions** [comment]
There probably is. I run navicat in eternal trial mode with the tool "RunAsDate". The tool sets the date to the installationdate of navicat and executes it, then it changes the date back.

**Comment by cmbsolutions** [comment]
Don't know if there is. But you could make a script like this`date1=$(date +%m)
date2=$(date +%d)
date3=$(date +%H)
date4=$(date +%M)
date5=20
sudo date =$date1$date2$date3$date4$date5
open "/Applications/Application.app"
sudo ntpdate -u time.euro.apple.com`

**Comment by chenzhixiang111** [comment]
> Don't know if there is. But you could make a script like this `date1=$(date +%m) date2=$(date +%d) date3=$(date +%H) date4=$(date +%M) date5=20 sudo date =$date1$date2$date3$date4$date5 open "/Applications/Application.app" sudo ntpdate -u time.euro.apple.com`

thanks : )
